// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/compass-logo/Bearing.tsx": () => import("../components/mockups/compass-logo/Bearing.tsx"),
  "./components/mockups/compass-logo/TrueNorth.tsx": () => import("../components/mockups/compass-logo/TrueNorth.tsx"),
  "./components/mockups/compass-logo/Wayfinder.tsx": () => import("../components/mockups/compass-logo/Wayfinder.tsx"),
  "./components/mockups/feed-variants/Colleague.tsx": () => import("../components/mockups/feed-variants/Colleague.tsx"),
  "./components/mockups/feed-variants/CommonGround.tsx": () => import("../components/mockups/feed-variants/CommonGround.tsx"),
  "./components/mockups/feed-variants/Hybrid.tsx": () => import("../components/mockups/feed-variants/Hybrid.tsx"),
  "./components/mockups/feed-variants/Signal.tsx": () => import("../components/mockups/feed-variants/Signal.tsx")
};
