// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/capture-variants/EditorialManuscript.tsx": () => import("../components/mockups/capture-variants/EditorialManuscript.tsx"),
  "./components/mockups/capture-variants/ThreePromptQuickCapture.tsx": () => import("../components/mockups/capture-variants/ThreePromptQuickCapture.tsx"),
  "./components/mockups/capture-variants/ThreePromptWithRail.tsx": () => import("../components/mockups/capture-variants/ThreePromptWithRail.tsx"),
  "./components/mockups/capture-variants/TwoColumnConversation.tsx": () => import("../components/mockups/capture-variants/TwoColumnConversation.tsx"),
  "./components/mockups/compass-logo/Bearing.tsx": () => import("../components/mockups/compass-logo/Bearing.tsx"),
  "./components/mockups/compass-logo/TrueNorth.tsx": () => import("../components/mockups/compass-logo/TrueNorth.tsx"),
  "./components/mockups/compass-logo/Wayfinder.tsx": () => import("../components/mockups/compass-logo/Wayfinder.tsx"),
  "./components/mockups/cover-variants/DataAsHero.tsx": () => import("../components/mockups/cover-variants/DataAsHero.tsx"),
  "./components/mockups/cover-variants/EditorialStatement.tsx": () => import("../components/mockups/cover-variants/EditorialStatement.tsx"),
  "./components/mockups/cover-variants/HybridDataPeek.tsx": () => import("../components/mockups/cover-variants/HybridDataPeek.tsx"),
  "./components/mockups/cover-variants/HybridDataPeekAnimated.tsx": () => import("../components/mockups/cover-variants/HybridDataPeekAnimated.tsx"),
  "./components/mockups/cover-variants/ProductPeek.tsx": () => import("../components/mockups/cover-variants/ProductPeek.tsx"),
  "./components/mockups/feed-variants/Briefing.tsx": () => import("../components/mockups/feed-variants/Briefing.tsx"),
  "./components/mockups/feed-variants/Colleague.tsx": () => import("../components/mockups/feed-variants/Colleague.tsx"),
  "./components/mockups/feed-variants/CommonGround.tsx": () => import("../components/mockups/feed-variants/CommonGround.tsx"),
  "./components/mockups/feed-variants/Companion.tsx": () => import("../components/mockups/feed-variants/Companion.tsx"),
  "./components/mockups/feed-variants/Hybrid.tsx": () => import("../components/mockups/feed-variants/Hybrid.tsx"),
  "./components/mockups/feed-variants/Library.tsx": () => import("../components/mockups/feed-variants/Library.tsx"),
  "./components/mockups/feed-variants/Signal.tsx": () => import("../components/mockups/feed-variants/Signal.tsx"),
  "./components/mockups/concept/NudgeOverlay.tsx": () => import("../components/mockups/concept/NudgeOverlay.tsx"),
  "./components/mockups/concept/NudgeOverlayB.tsx": () => import("../components/mockups/concept/NudgeOverlayB.tsx"),
  "./components/mockups/concept/NudgeOverlayC.tsx": () => import("../components/mockups/concept/NudgeOverlayC.tsx")
};
